spring.application.name=home
spring.datasource.url=jdbc:mysql://f02t0r.h.filess.io:61002/ecofesta_db_monthwere?useSSL=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.username=ecofesta_db_monthwere
spring.datasource.password=13813446c53a9751cfa584620e63d57699e2f4c3

# JPA 설정 (JPA를 사용하는 경우)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
