spring.application.name=home
spring.datasource.url=jdbc:mysql://h0xhzi.h.filess.io:3307/ecofesta_sever_stretchtoy?useSSL=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.username=ecofesta_sever_stretchtoy
spring.datasource.password=1bd2c4802a2b95a7627eec7597a9ad1f623ca988
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정 (JPA를 사용하는 경우)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
